# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/cenkalti/backoff
%global goipath         github.com/cenkalti/backoff
Version:                4.1.1

%gometa

%global common_description %{expand:
⏱ The exponential backoff algorithm in Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        ⏱ The exponential backoff algorithm in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 4.1.1-1%{?dist}
- Initial package

