# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/hashicorp/vault
%global goipath         github.com/hashicorp/vault
Version:                1.8.3

%gometa

%global common_description %{expand:
A tool for secrets management, encryption as a service, and privileged access
management.}

%global golicenses      LICENSE ui/app/adapters/license.js\\\
                        ui/app/components/license-banners.js\\\
                        ui/app/components/license-info.js\\\
                        ui/app/models/license.js\\\
                        ui/app/routes/vault/cluster/license.js\\\
                        ui/app/serializers/license.js\\\
                        ui/app/styles/components/license-banners.scss\\\
                        ui/app/templates/components/license-banners.hbs\\\
                        ui/app/templates/components/license-info.hbs\\\
                        ui/app/templates/vault/cluster/license.hbs\\\
                        website/content/api-docs/system/license.mdx
%global godocs          CHANGELOG.md CONTRIBUTING.md README.md api/README.md\\\
                        builtin/credential/aws/pkcs7/README.md\\\
                        builtin/credential/cert/test-fixtures/generate.txt\\\
                        command/agent/README.md\\\
                        physical/foundationdb/README.md\\\
                        plugins/database/mongodb/README.md\\\
                        plugins/database/mssql/README.md ui/MODULE_REPORT.md\\\
                        ui/README.md ui/lib/core/addon/helpers/changelog-url-\\\
                        for.js ui/lib/core/app/helpers/changelog-url-for.js\\\
                        ui/lib/core/stories/alert-banner.md\\\
                        ui/lib/core/stories/alert-inline.md\\\
                        ui/lib/core/stories/box-radio.md\\\
                        ui/lib/core/stories/chevron.md\\\
                        ui/lib/core/stories/confirm-action.md\\\
                        ui/lib/core/stories/confirm.md\\\
                        ui/lib/core/stories/doc-link.md\\\
                        ui/lib/core/stories/empty-state.md\\\
                        ui/lib/core/stories/form-field-groups.md\\\
                        ui/lib/core/stories/form-field.md\\\
                        ui/lib/core/stories/form-save-buttons.md\\\
                        ui/lib/core/stories/icon.md ui/lib/core/stories/info-\\\
                        table-row.md ui/lib/core/stories/info-table.md\\\
                        ui/lib/core/stories/layout-loading.md\\\
                        ui/lib/core/stories/linkable-item.md\\\
                        ui/lib/core/stories/list-view.md\\\
                        ui/lib/core/stories/masked-input.md\\\
                        ui/lib/core/stories/message-error.md\\\
                        ui/lib/core/stories/message.md\\\
                        ui/lib/core/stories/popup-menu.md\\\
                        ui/lib/core/stories/search-select.md\\\
                        ui/lib/core/stories/select.md\\\
                        ui/lib/core/stories/toggle-button.md\\\
                        ui/lib/core/stories/ttl-form.md\\\
                        ui/lib/core/stories/ttl-picker.md\\\
                        ui/lib/core/stories/ttl-picker2.md\\\
                        ui/lib/core/stories/vault-logo-spinner.md\\\
                        ui/lib/core/stories/toolbar/toolbar-actions.md\\\
                        ui/lib/core/stories/toolbar/toolbar-download-\\\
                        button.md ui/lib/core/stories/toolbar/toolbar-\\\
                        filters.md ui/lib/core/stories/toolbar/toolbar-\\\
                        link.md ui/lib/core/stories/toolbar/toolbar-secret-\\\
                        link.md ui/lib/core/stories/toolbar/toolbar.md\\\
                        ui/public/robots.txt ui/stories/alert-popup.md\\\
                        ui/stories/auth-form.md ui/stories/file-to-array-\\\
                        buffer.md ui/stories/selectable-card.md\\\
                        ui/stories/toggle.md ui/stories/auth-config-\\\
                        form/config.md ui/stories/auth-config-form/options.md\\\
                        website/README.md\\\
                        website/components/columns/README.md\\\
                        website/components/inline-tag/README.md docs\\\
                        website/content/security.mdx website/content/api-\\\
                        docs/index.mdx website/content/api-docs/libraries.mdx\\\
                        website/content/api-docs/relatedtools.mdx\\\
                        website/content/api-docs/auth/alicloud.mdx\\\
                        website/content/api-docs/auth/app-id.mdx\\\
                        website/content/api-docs/auth/approle.mdx\\\
                        website/content/api-docs/auth/aws.mdx\\\
                        website/content/api-docs/auth/azure.mdx\\\
                        website/content/api-docs/auth/cert.mdx\\\
                        website/content/api-docs/auth/cf.mdx\\\
                        website/content/api-docs/auth/gcp.mdx\\\
                        website/content/api-docs/auth/github.mdx\\\
                        website/content/api-docs/auth/index.mdx\\\
                        website/content/api-docs/auth/jwt.mdx\\\
                        website/content/api-docs/auth/kerberos.mdx\\\
                        website/content/api-docs/auth/kubernetes.mdx\\\
                        website/content/api-docs/auth/ldap.mdx\\\
                        website/content/api-docs/auth/oci.mdx\\\
                        website/content/api-docs/auth/okta.mdx\\\
                        website/content/api-docs/auth/radius.mdx\\\
                        website/content/api-docs/auth/token.mdx\\\
                        website/content/api-docs/auth/userpass.mdx\\\
                        website/content/api-docs/secret/ad.mdx\\\
                        website/content/api-docs/secret/alicloud.mdx\\\
                        website/content/api-docs/secret/aws.mdx\\\
                        website/content/api-docs/secret/azure.mdx\\\
                        website/content/api-docs/secret/cassandra.mdx\\\
                        website/content/api-docs/secret/consul.mdx\\\
                        website/content/api-docs/secret/cubbyhole.mdx\\\
                        website/content/api-docs/secret/gcp.mdx\\\
                        website/content/api-docs/secret/gcpkms.mdx\\\
                        website/content/api-docs/secret/index.mdx\\\
                        website/content/api-docs/secret/kmip.mdx\\\
                        website/content/api-docs/secret/mongodbatlas.mdx\\\
                        website/content/api-docs/secret/nomad.mdx\\\
                        website/content/api-docs/secret/openldap.mdx\\\
                        website/content/api-docs/secret/pki.mdx\\\
                        website/content/api-docs/secret/rabbitmq.mdx\\\
                        website/content/api-docs/secret/ssh.mdx\\\
                        website/content/api-docs/secret/terraform.mdx\\\
                        website/content/api-docs/secret/totp.mdx\\\
                        website/content/api-docs/secret/transform.mdx\\\
                        website/content/api-docs/secret/transit.mdx\\\
                        website/content/api-\\\
                        docs/secret/databases/cassandra.mdx\\\
                        website/content/api-\\\
                        docs/secret/databases/couchbase.mdx\\\
                        website/content/api-\\\
                        docs/secret/databases/elasticdb.mdx\\\
                        website/content/api-docs/secret/databases/hanadb.mdx\\\
                        website/content/api-docs/secret/databases/index.mdx\\\
                        website/content/api-\\\
                        docs/secret/databases/influxdb.mdx\\\
                        website/content/api-docs/secret/databases/mongodb.mdx\\\
                        website/content/api-\\\
                        docs/secret/databases/mongodbatlas.mdx\\\
                        website/content/api-docs/secret/databases/mssql.mdx\\\
                        website/content/api-docs/secret/databases/mysql-\\\
                        maria.mdx website/content/api-\\\
                        docs/secret/databases/oracle.mdx website/content/api-\\\
                        docs/secret/databases/postgresql.mdx\\\
                        website/content/api-\\\
                        docs/secret/databases/redshift.mdx\\\
                        website/content/api-\\\
                        docs/secret/databases/snowflake.mdx\\\
                        website/content/api-docs/secret/identity/entity-\\\
                        alias.mdx website/content/api-\\\
                        docs/secret/identity/entity.mdx website/content/api-\\\
                        docs/secret/identity/group-alias.mdx\\\
                        website/content/api-docs/secret/identity/group.mdx\\\
                        website/content/api-docs/secret/identity/index.mdx\\\
                        website/content/api-docs/secret/identity/lookup.mdx\\\
                        website/content/api-docs/secret/identity/tokens.mdx\\\
                        website/content/api-docs/secret/key-\\\
                        management/awskms.mdx website/content/api-\\\
                        docs/secret/key-management/azurekeyvault.mdx\\\
                        website/content/api-docs/secret/key-\\\
                        management/index.mdx website/content/api-\\\
                        docs/secret/kv/index.mdx website/content/api-\\\
                        docs/secret/kv/kv-v1.mdx website/content/api-\\\
                        docs/secret/kv/kv-v2.mdx website/content/api-\\\
                        docs/system/audit-hash.mdx website/content/api-\\\
                        docs/system/audit.mdx website/content/api-\\\
                        docs/system/auth.mdx website/content/api-\\\
                        docs/system/capabilities-accessor.mdx\\\
                        website/content/api-docs/system/capabilities-self.mdx\\\
                        website/content/api-docs/system/capabilities.mdx\\\
                        website/content/api-docs/system/config-auditing.mdx\\\
                        website/content/api-docs/system/config-control-\\\
                        group.mdx website/content/api-docs/system/config-\\\
                        cors.mdx website/content/api-docs/system/config-\\\
                        reload.mdx website/content/api-docs/system/config-\\\
                        state.mdx website/content/api-docs/system/config-\\\
                        ui.mdx website/content/api-docs/system/control-\\\
                        group.mdx website/content/api-docs/system/generate-\\\
                        recovery-token.mdx website/content/api-\\\
                        docs/system/generate-root.mdx website/content/api-\\\
                        docs/system/health.mdx website/content/api-\\\
                        docs/system/host-info.mdx website/content/api-\\\
                        docs/system/index.mdx website/content/api-\\\
                        docs/system/init.mdx website/content/api-\\\
                        docs/system/internal-counters.mdx\\\
                        website/content/api-docs/system/internal-specs-\\\
                        openapi.mdx website/content/api-docs/system/internal-\\\
                        ui-feature.mdx website/content/api-\\\
                        docs/system/internal-ui-mounts.mdx\\\
                        website/content/api-docs/system/key-status.mdx\\\
                        website/content/api-docs/system/leader.mdx\\\
                        website/content/api-docs/system/lease-count-\\\
                        quotas.mdx website/content/api-docs/system/leases.mdx\\\
                        website/content/api-docs/system/metrics.mdx\\\
                        website/content/api-docs/system/monitor.mdx\\\
                        website/content/api-docs/system/mounts.mdx\\\
                        website/content/api-docs/system/namespaces.mdx\\\
                        website/content/api-docs/system/plugins-catalog.mdx\\\
                        website/content/api-docs/system/plugins-reload-\\\
                        backend.mdx website/content/api-docs/system/policies-\\\
                        password.mdx website/content/api-\\\
                        docs/system/policies.mdx website/content/api-\\\
                        docs/system/policy.mdx website/content/api-\\\
                        docs/system/pprof.mdx website/content/api-\\\
                        docs/system/quotas-config.mdx website/content/api-\\\
                        docs/system/rate-limit-quotas.mdx\\\
                        website/content/api-docs/system/raw.mdx\\\
                        website/content/api-docs/system/rekey-recovery-\\\
                        key.mdx website/content/api-docs/system/rekey.mdx\\\
                        website/content/api-docs/system/remount.mdx\\\
                        website/content/api-docs/system/rotate-config.mdx\\\
                        website/content/api-docs/system/rotate.mdx\\\
                        website/content/api-docs/system/seal-status.mdx\\\
                        website/content/api-docs/system/seal.mdx\\\
                        website/content/api-docs/system/sealwrap-rewrap.mdx\\\
                        website/content/api-docs/system/step-down.mdx\\\
                        website/content/api-docs/system/tools.mdx\\\
                        website/content/api-docs/system/unseal.mdx\\\
                        website/content/api-docs/system/wrapping-lookup.mdx\\\
                        website/content/api-docs/system/wrapping-rewrap.mdx\\\
                        website/content/api-docs/system/wrapping-unwrap.mdx\\\
                        website/content/api-docs/system/wrapping-wrap.mdx\\\
                        website/content/api-docs/system/mfa/duo.mdx\\\
                        website/content/api-docs/system/mfa/index.mdx\\\
                        website/content/api-docs/system/mfa/okta.mdx\\\
                        website/content/api-docs/system/mfa/pingid.mdx\\\
                        website/content/api-docs/system/mfa/totp.mdx\\\
                        website/content/api-docs/system/replication/index.mdx\\\
                        website/content/api-\\\
                        docs/system/replication/replication-dr.mdx\\\
                        website/content/api-\\\
                        docs/system/replication/replication-performance.mdx\\\
                        website/content/api-docs/system/storage/index.mdx\\\
                        website/content/api-docs/system/storage/raft.mdx\\\
                        website/content/api-\\\
                        docs/system/storage/raftautopilot.mdx\\\
                        website/content/api-\\\
                        docs/system/storage/raftautosnapshots.mdx\\\
                        website/content/guides/getting-started.mdx\\\
                        website/content/guides/index.mdx\\\
                        website/content/guides/encryption/index.mdx\\\
                        website/content/guides/encryption/spring-demo.mdx\\\
                        website/content/guides/encryption/transit-rewrap.mdx\\\
                        website/content/guides/encryption/transit.mdx\\\
                        website/content/guides/identity/approle-trusted-\\\
                        entities.mdx\\\
                        website/content/guides/identity/authentication.mdx\\\
                        website/content/guides/identity/control-groups.mdx\\\
                        website/content/guides/identity/identity.mdx\\\
                        website/content/guides/identity/index.mdx\\\
                        website/content/guides/identity/lease.mdx\\\
                        website/content/guides/identity/policies.mdx\\\
                        website/content/guides/identity/policy-templating.mdx\\\
                        website/content/guides/identity/secure-intro.mdx\\\
                        website/content/guides/identity/sentinel.mdx\\\
                        website/content/guides/operations/autounseal-aws-\\\
                        kms.mdx website/content/guides/operations/deployment-\\\
                        guide.mdx website/content/guides/operations/disaster-\\\
                        recovery.mdx\\\
                        website/content/guides/operations/generate-root.mdx\\\
                        website/content/guides/operations/index.mdx\\\
                        website/content/guides/operations/monitoring.mdx\\\
                        website/content/guides/operations/mount-filter.mdx\\\
                        website/content/guides/operations/multi-tenant.mdx\\\
                        website/content/guides/operations/performance-\\\
                        nodes.mdx website/content/guides/operations/plugin-\\\
                        backends.mdx\\\
                        website/content/guides/operations/production.mdx\\\
                        website/content/guides/operations/reference-\\\
                        architecture.mdx\\\
                        website/content/guides/operations/rekeying-and-\\\
                        rotating.mdx\\\
                        website/content/guides/operations/replication.mdx\\\
                        website/content/guides/operations/seal-wrap.mdx\\\
                        website/content/guides/operations/vault-ha-consul.mdx\\\
                        website/content/guides/secret-mgmt/app-\\\
                        integration.mdx website/content/guides/secret-\\\
                        mgmt/cubbyhole.mdx website/content/guides/secret-\\\
                        mgmt/db-root-rotation.mdx\\\
                        website/content/guides/secret-mgmt/dynamic-\\\
                        secrets.mdx website/content/guides/secret-\\\
                        mgmt/index.mdx website/content/guides/secret-\\\
                        mgmt/pki-engine.mdx website/content/guides/secret-\\\
                        mgmt/ssh-otp.mdx website/content/guides/secret-\\\
                        mgmt/static-secrets.mdx\\\
                        website/content/guides/secret-mgmt/versioned-kv.mdx\\\
                        website/content/intro/index.mdx\\\
                        website/content/intro/getting-started/apis.mdx\\\
                        website/content/intro/getting-\\\
                        started/authentication.mdx\\\
                        website/content/intro/getting-started/deploy.mdx\\\
                        website/content/intro/getting-started/dev-server.mdx\\\
                        website/content/intro/getting-started/dynamic-\\\
                        secrets.mdx website/content/intro/getting-\\\
                        started/first-secret.mdx\\\
                        website/content/intro/getting-started/help.mdx\\\
                        website/content/intro/getting-started/index.mdx\\\
                        website/content/intro/getting-started/next-steps.mdx\\\
                        website/content/intro/getting-started/policies.mdx\\\
                        website/content/intro/getting-started/secrets-\\\
                        engines.mdx website/content/partials/aws-auth-\\\
                        metadata-fix.mdx website/content/partials/aws-auth-\\\
                        metadata-issue.mdx website/content/partials/aws-imds-\\\
                        timeout-upgrade.mdx website/content/partials/aws-\\\
                        imds-timeout.mdx website/content/partials/aws-\\\
                        invalid-header-fix.mdx website/content/partials/aws-\\\
                        invalid-header.mdx website/content/partials/aws-sts-\\\
                        issue.mdx website/content/partials/builds-without-\\\
                        ui.mdx website/content/partials/enterprise-\\\
                        licenses.mdx website/content/partials/ldap-upndomain-\\\
                        issue.mdx website/content/partials/okta-group-\\\
                        pagination.mdx website/content/partials/primary-\\\
                        cluster-addr-change.mdx\\\
                        website/content/partials/tokenfields.mdx\\\
                        website/content/partials/tokenstorefields.mdx\\\
                        website/content/partials/transform-upgrade.mdx docs\\\
                        docs changelog/10072.txt changelog/10077.txt\\\
                        changelog/10131.txt changelog/10181.txt\\\
                        changelog/10231.txt changelog/10365.txt\\\
                        changelog/10375.txt changelog/10384.txt\\\
                        changelog/10386.txt changelog/10416.txt\\\
                        changelog/10417.txt changelog/10424.txt\\\
                        changelog/10433.txt changelog/10444.txt\\\
                        changelog/10456.txt changelog/10487.txt\\\
                        changelog/10489.txt changelog/10490.txt\\\
                        changelog/10491.txt changelog/10498.txt\\\
                        changelog/10514.txt changelog/10520.txt\\\
                        changelog/10536.txt changelog/10537.txt\\\
                        changelog/10546.txt changelog/10556.txt\\\
                        changelog/10558.txt changelog/10579.txt\\\
                        changelog/10588.txt changelog/10596.txt\\\
                        changelog/10603.txt changelog/10609.txt\\\
                        changelog/10613.txt changelog/10650.txt\\\
                        changelog/10653.txt changelog/10655.txt\\\
                        changelog/10677.txt changelog/10684.txt\\\
                        changelog/10689.txt changelog/10705.txt\\\
                        changelog/10708.txt changelog/10725.txt\\\
                        changelog/10726.txt changelog/10730.txt\\\
                        changelog/10743.txt changelog/10744.txt\\\
                        changelog/10756.txt changelog/10757.txt\\\
                        changelog/10758.txt changelog/10759.txt\\\
                        changelog/10766.txt changelog/10767.txt\\\
                        changelog/10812.txt changelog/10826.txt\\\
                        changelog/10833.txt changelog/10834.txt\\\
                        changelog/10848.txt changelog/10850.txt\\\
                        changelog/10855.txt changelog/10858.txt\\\
                        changelog/10877.txt changelog/10901.txt\\\
                        changelog/10904.txt changelog/10906.txt\\\
                        changelog/10919.txt changelog/10927.txt\\\
                        changelog/10931.txt changelog/10938.txt\\\
                        changelog/10942.txt changelog/10949.txt\\\
                        changelog/10951.txt changelog/10952.txt\\\
                        changelog/10953.txt changelog/10964.txt\\\
                        changelog/10980.txt changelog/10982.txt\\\
                        changelog/10992.txt changelog/10995.txt\\\
                        changelog/10996.txt changelog/10997.txt\\\
                        changelog/11011.txt changelog/11015.txt\\\
                        changelog/11018.txt changelog/11022.txt\\\
                        changelog/11094.txt changelog/11113.txt\\\
                        changelog/11119.txt changelog/11127.txt\\\
                        changelog/11129.txt changelog/11142.txt\\\
                        changelog/11143.txt changelog/11182.txt\\\
                        changelog/11213.txt changelog/11226.txt\\\
                        changelog/11231.txt changelog/11247.txt\\\
                        changelog/11252.txt changelog/11256.txt\\\
                        changelog/11258.txt changelog/11259.txt\\\
                        changelog/11260.txt changelog/11262.txt\\\
                        changelog/11269.txt changelog/11283.txt\\\
                        changelog/11284.txt changelog/11288.txt\\\
                        changelog/11289.txt changelog/11294.txt\\\
                        changelog/11324.txt changelog/11345.txt\\\
                        changelog/11360.txt changelog/11364.txt\\\
                        changelog/11365.txt changelog/11366.txt\\\
                        changelog/11367.txt changelog/11371.txt\\\
                        changelog/11377.txt changelog/11388.txt\\\
                        changelog/11404.txt changelog/11408.txt\\\
                        changelog/11442.txt changelog/11447.txt\\\
                        changelog/11451.txt changelog/11453.txt\\\
                        changelog/11473.txt changelog/11495.txt\\\
                        changelog/11500.txt changelog/11502.txt\\\
                        changelog/11506.txt changelog/11517.txt\\\
                        changelog/11530.txt changelog/11532.txt\\\
                        changelog/11541.txt changelog/11562.txt\\\
                        changelog/11576.txt changelog/11585.txt\\\
                        changelog/11586.txt changelog/11588.txt\\\
                        changelog/11596.txt changelog/11597.txt\\\
                        changelog/11600.txt changelog/11607.txt\\\
                        changelog/11628.txt changelog/11638.txt\\\
                        changelog/11641.txt changelog/11647.txt\\\
                        changelog/11650.txt changelog/11672.txt\\\
                        changelog/11680.txt changelog/11696.txt\\\
                        changelog/11705.txt changelog/11708.txt\\\
                        changelog/11759.txt changelog/11775.txt\\\
                        changelog/11778.txt changelog/11784.txt\\\
                        changelog/11785.txt changelog/11795.txt\\\
                        changelog/11796.txt changelog/11802.txt\\\
                        changelog/11820.txt changelog/11826.txt\\\
                        changelog/11836.txt changelog/11838.txt\\\
                        changelog/11861.txt changelog/11864.txt\\\
                        changelog/11872.txt changelog/11878.txt\\\
                        changelog/11884.txt changelog/11895.txt\\\
                        changelog/11899.txt changelog/11907.txt\\\
                        changelog/11934.txt changelog/11942.txt\\\
                        changelog/11956.txt changelog/11957.txt\\\
                        changelog/11958.txt changelog/11963.txt\\\
                        changelog/11970.txt changelog/11975.txt\\\
                        changelog/11984.txt changelog/11992.txt\\\
                        changelog/11995.txt changelog/11997.txt\\\
                        changelog/12003.txt changelog/12008.txt\\\
                        changelog/12016.txt changelog/12019.txt\\\
                        changelog/12020.txt changelog/12023.txt\\\
                        changelog/12024.txt changelog/12025.txt\\\
                        changelog/12026.txt changelog/12031.txt\\\
                        changelog/12034.txt changelog/12035.txt\\\
                        changelog/12042.txt changelog/12049.txt\\\
                        changelog/12071.txt changelog/12073.txt\\\
                        changelog/12079.txt changelog/12087.txt\\\
                        changelog/12111.txt changelog/12151.txt\\\
                        changelog/12163.txt changelog/12175.txt\\\
                        changelog/12229.txt changelog/12245.txt\\\
                        changelog/12258.txt changelog/12300.txt\\\
                        changelog/12339.txt changelog/12340.txt\\\
                        changelog/12348.txt changelog/12351.txt\\\
                        changelog/12354.txt changelog/12371.txt\\\
                        changelog/12377.txt changelog/12378.txt\\\
                        changelog/12379.txt changelog/12388.txt\\\
                        changelog/12408.txt changelog/12409.txt\\\
                        changelog/12418.txt changelog/12473.txt\\\
                        changelog/12478.txt changelog/12514.txt\\\
                        changelog/12534.txt changelog/12550.txt\\\
                        changelog/12563.txt changelog/12599.txt\\\
                        changelog/12635.txt changelog/9972.txt\\\
                        changelog/README.md changelog/_ 1686.txt\\\
                        changelog/_10959.txt changelog/_1622.txt\\\
                        changelog/_1633.txt changelog/_1637.txt\\\
                        changelog/_1642.txt changelog/_1656.txt\\\
                        changelog/_1659.txt changelog/_1663.txt\\\
                        changelog/_1680.txt changelog/_1691.txt\\\
                        changelog/_1705.txt changelog/_1712.txt\\\
                        changelog/_1739.txt changelog/_1757.txt\\\
                        changelog/_1792.txt changelog/_1819.txt\\\
                        changelog/_2021Jan20.txt changelog/_2021Jan26.txt\\\
                        changelog/_2021Jul21_license.txt changelog/_2071.txt\\\
                        changelog/changelog.tmpl dependencies/2-25-21/deps-\\\
                        upgrade-output.txt dependencies/2-25-21/deps-\\\
                        upgrade.txt internalshared/README.md sdk/README.md\\\
                        sdk/database/dbplugin/README.md sdk/queue/README.md\\\
                        serviceregistration/kubernetes/testing/README.md\\\
                        terraform/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A tool for secrets management, encryption as a service, and privileged access management

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/monitoring/apiv3)
BuildRequires:  golang(cloud.google.com/go/spanner)
BuildRequires:  golang(cloud.google.com/go/storage)
BuildRequires:  golang(github.com/aerospike/aerospike-client-go)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/providers)
BuildRequires:  golang(github.com/aliyun/aliyun-oss-go-sdk/oss)
BuildRequires:  golang(github.com/armon/go-metrics)
BuildRequires:  golang(github.com/armon/go-metrics/circonus)
BuildRequires:  golang(github.com/armon/go-metrics/datadog)
BuildRequires:  golang(github.com/armon/go-metrics/prometheus)
BuildRequires:  golang(github.com/armon/go-proxyproto)
BuildRequires:  golang(github.com/armon/go-radix)
BuildRequires:  golang(github.com/asaskevich/govalidator)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/arn)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/client)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials/stscreds)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/defaults)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/ec2metadata)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/endpoints)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/request)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/dynamodb)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/ec2)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/iam)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/iam/iamiface)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/s3)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/sts)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/sts/stsiface)
BuildRequires:  golang(github.com/Azure/azure-storage-blob-go/azblob)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/adal)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure)
BuildRequires:  golang(github.com/cenkalti/backoff/v3)
BuildRequires:  golang(github.com/chrismalek/oktasdk-go/okta)
BuildRequires:  golang(github.com/cockroachdb/cockroach-go/crdb)
BuildRequires:  golang(github.com/coreos/go-semver/semver)
BuildRequires:  golang(github.com/coreos/go-systemd/daemon)
BuildRequires:  golang(github.com/denisenkom/go-mssqldb)
BuildRequires:  golang(github.com/docker/docker/api/types)
BuildRequires:  golang(github.com/docker/docker/api/types/container)
BuildRequires:  golang(github.com/docker/docker/api/types/network)
BuildRequires:  golang(github.com/docker/docker/api/types/strslice)
BuildRequires:  golang(github.com/docker/docker/client)
BuildRequires:  golang(github.com/docker/docker/pkg/archive)
BuildRequires:  golang(github.com/docker/docker/pkg/ioutils)
BuildRequires:  golang(github.com/docker/go-connections/nat)
BuildRequires:  golang(github.com/duosecurity/duo_api_golang)
BuildRequires:  golang(github.com/duosecurity/duo_api_golang/authapi)
BuildRequires:  golang(github.com/dustin/go-humanize)
BuildRequires:  golang(github.com/elazarl/go-bindata-assetfs)
BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/fatih/structs)
BuildRequires:  golang(github.com/ghodss/yaml)
BuildRequires:  golang(github.com/go-errors/errors)
BuildRequires:  golang(github.com/go-ldap/ldap/v3)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/go-test/deep)
BuildRequires:  golang(github.com/gocql/gocql)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/snappy)
BuildRequires:  golang(github.com/google/go-github/github)
BuildRequires:  golang(github.com/google/go-metrics-stackdriver)
BuildRequires:  golang(github.com/google/go-metrics-stackdriver/vault)
BuildRequires:  golang(github.com/hashicorp/consul-template/config)
BuildRequires:  golang(github.com/hashicorp/consul-template/logging)
BuildRequires:  golang(github.com/hashicorp/consul-template/manager)
BuildRequires:  golang(github.com/hashicorp/consul/api)
BuildRequires:  golang(github.com/hashicorp/errwrap)
BuildRequires:  golang(github.com/hashicorp/go-cleanhttp)
BuildRequires:  golang(github.com/hashicorp/go-discover)
BuildRequires:  golang(github.com/hashicorp/go-discover/provider/k8s)
BuildRequires:  golang(github.com/hashicorp/go-gcp-common/gcputil)
BuildRequires:  golang(github.com/hashicorp/go-hclog)
BuildRequires:  golang(github.com/hashicorp/go-immutable-radix)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/entropy)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/wrappers/aead)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/wrappers/alicloudkms)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/wrappers/awskms)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/wrappers/azurekeyvault)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/wrappers/gcpckms)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/wrappers/ocikms)
BuildRequires:  golang(github.com/hashicorp/go-kms-wrapping/wrappers/transit)
BuildRequires:  golang(github.com/hashicorp/go-memdb)
BuildRequires:  golang(github.com/hashicorp/go-multierror)
BuildRequires:  golang(github.com/hashicorp/go-plugin)
BuildRequires:  golang(github.com/hashicorp/go-raftchunking)
BuildRequires:  golang(github.com/hashicorp/go-retryablehttp)
BuildRequires:  golang(github.com/hashicorp/go-rootcerts)
BuildRequires:  golang(github.com/hashicorp/go-sockaddr)
BuildRequires:  golang(github.com/hashicorp/go-syslog)
BuildRequires:  golang(github.com/hashicorp/go-uuid)
BuildRequires:  golang(github.com/hashicorp/go-version)
BuildRequires:  golang(github.com/hashicorp/golang-lru)
BuildRequires:  golang(github.com/hashicorp/hcl)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/ast)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/printer)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/token)
BuildRequires:  golang(github.com/hashicorp/nomad/api)
BuildRequires:  golang(github.com/hashicorp/raft)
BuildRequires:  golang(github.com/hashicorp/raft-autopilot)
BuildRequires:  golang(github.com/hashicorp/raft-boltdb/v2)
BuildRequires:  golang(github.com/hashicorp/raft-snapshot)
BuildRequires:  golang(github.com/influxdata/influxdb/client/v2)
BuildRequires:  golang(github.com/jcmturner/gokrb5/v8/spnego)
BuildRequires:  golang(github.com/jefferai/isbadcipher)
BuildRequires:  golang(github.com/jefferai/jsonx)
BuildRequires:  golang(github.com/joyent/triton-go)
BuildRequires:  golang(github.com/joyent/triton-go/authentication)
BuildRequires:  golang(github.com/joyent/triton-go/errors)
BuildRequires:  golang(github.com/joyent/triton-go/storage)
BuildRequires:  golang(github.com/keybase/go-crypto/openpgp)
BuildRequires:  golang(github.com/keybase/go-crypto/openpgp/packet)
BuildRequires:  golang(github.com/kr/pretty)
BuildRequires:  golang(github.com/kr/text)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mattn/go-colorable)
BuildRequires:  golang(github.com/mholt/archiver)
BuildRequires:  golang(github.com/michaelklishin/rabbit-hole)
BuildRequires:  golang(github.com/mitchellh/cli)
BuildRequires:  golang(github.com/mitchellh/copystructure)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/mitchellh/go-testing-interface)
BuildRequires:  golang(github.com/mitchellh/go-wordwrap)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/mitchellh/reflectwalk)
BuildRequires:  golang(github.com/natefinch/atomic)
BuildRequires:  golang(github.com/ncw/swift)
BuildRequires:  golang(github.com/NYTimes/gziphandler)
BuildRequires:  golang(github.com/oklog/run)
BuildRequires:  golang(github.com/okta/okta-sdk-golang/v2/okta)
BuildRequires:  golang(github.com/oracle/oci-go-sdk/common)
BuildRequires:  golang(github.com/oracle/oci-go-sdk/common/auth)
BuildRequires:  golang(github.com/oracle/oci-go-sdk/objectstorage)
BuildRequires:  golang(github.com/patrickmn/go-cache)
BuildRequires:  golang(github.com/pierrec/lz4)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/posener/complete)
BuildRequires:  golang(github.com/pquerna/otp)
BuildRequires:  golang(github.com/pquerna/otp/totp)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus)
BuildRequires:  golang(github.com/prometheus/common/expfmt)
BuildRequires:  golang(github.com/rboyer/safeio)
BuildRequires:  golang(github.com/ryanuber/columnize)
BuildRequires:  golang(github.com/ryanuber/go-glob)
BuildRequires:  golang(github.com/samuel/go-zookeeper/zk)
BuildRequires:  golang(github.com/SAP/go-hdb/driver)
BuildRequires:  golang(github.com/sethvargo/go-limiter)
BuildRequires:  golang(github.com/sethvargo/go-limiter/httplimit)
BuildRequires:  golang(github.com/sethvargo/go-limiter/memorystore)
BuildRequires:  golang(github.com/shirou/gopsutil/cpu)
BuildRequires:  golang(github.com/shirou/gopsutil/disk)
BuildRequires:  golang(github.com/shirou/gopsutil/host)
BuildRequires:  golang(github.com/shirou/gopsutil/mem)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(go.etcd.io/bbolt)
BuildRequires:  golang(go.etcd.io/etcd/client)
BuildRequires:  golang(go.etcd.io/etcd/clientv3)
BuildRequires:  golang(go.etcd.io/etcd/clientv3/concurrency)
BuildRequires:  golang(go.etcd.io/etcd/pkg/transport)
BuildRequires:  golang(go.mongodb.org/mongo-driver/mongo)
BuildRequires:  golang(go.mongodb.org/mongo-driver/mongo/options)
BuildRequires:  golang(go.mongodb.org/mongo-driver/mongo/readpref)
BuildRequires:  golang(go.mongodb.org/mongo-driver/mongo/writeconcern)
BuildRequires:  golang(go.mongodb.org/mongo-driver/x/mongo/driver/connstring)
BuildRequires:  golang(go.opentelemetry.io/otel/attribute)
BuildRequires:  golang(go.opentelemetry.io/otel/codes)
BuildRequires:  golang(go.opentelemetry.io/otel/sdk/trace)
BuildRequires:  golang(go.opentelemetry.io/otel/trace)
BuildRequires:  golang(go.uber.org/atomic)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(golang.org/x/crypto/blake2b)
BuildRequires:  golang(golang.org/x/crypto/chacha20poly1305)
BuildRequires:  golang(golang.org/x/crypto/cryptobyte)
BuildRequires:  golang(golang.org/x/crypto/cryptobyte/asn1)
BuildRequires:  golang(golang.org/x/crypto/curve25519)
BuildRequires:  golang(golang.org/x/crypto/ed25519)
BuildRequires:  golang(golang.org/x/crypto/hkdf)
BuildRequires:  golang(golang.org/x/crypto/ssh)
BuildRequires:  golang(golang.org/x/crypto/ssh/agent)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/net/http/httpproxy)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(golang.org/x/net/idna)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/term)
BuildRequires:  golang(golang.org/x/time/rate)
BuildRequires:  golang(google.golang.org/api/googleapi)
BuildRequires:  golang(google.golang.org/api/iamcredentials/v1)
BuildRequires:  golang(google.golang.org/api/iterator)
BuildRequires:  golang(google.golang.org/api/option)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/grpclog)
BuildRequires:  golang(google.golang.org/grpc/keepalive)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(google.golang.org/protobuf/proto)
BuildRequires:  golang(google.golang.org/protobuf/reflect/protoreflect)
BuildRequires:  golang(google.golang.org/protobuf/runtime/protoimpl)
BuildRequires:  golang(google.golang.org/protobuf/types/known/anypb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/structpb)
BuildRequires:  golang(google.golang.org/protobuf/types/known/timestamppb)
BuildRequires:  golang(gopkg.in/mgo.v2)
BuildRequires:  golang(gopkg.in/square/go-jose.v2)
BuildRequires:  golang(gopkg.in/square/go-jose.v2/jwt)
BuildRequires:  golang(layeh.com/radius)
BuildRequires:  golang(layeh.com/radius/rfc2865)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/services/sts)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/timestamp)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(github.com/hashicorp/go-raftchunking/types)
BuildRequires:  golang(github.com/mongodb/go-client-mongodb-atlas/mongodbatlas)
BuildRequires:  golang(github.com/okta/okta-sdk-golang/v2/okta/query)
BuildRequires:  golang(github.com/ory/dockertest)
BuildRequires:  golang(github.com/ory/dockertest/v3)
BuildRequires:  golang(github.com/Sectorbob/mlab-ns2/gae/ns/digest)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/mock)
BuildRequires:  golang(go.uber.org/goleak)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/vault %{goipath}
for cmd in plugins/database/mongodb/mongodb-database-plugin plugins/database/mysql/mysql-database-plugin plugins/database/mysql/mysql-legacy-database-plugin plugins/database/postgresql/postgresql-database-plugin plugins/database/cassandra/cassandra-database-plugin plugins/database/mssql/mssql-database-plugin plugins/database/hana/hana-database-plugin plugins/database/redshift/redshift-database-plugin plugins/database/influxdb/influxdb-database-plugin; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE ui/app/adapters/license.js
%license ui/app/components/license-banners.js ui/app/components/license-info.js
%license ui/app/models/license.js ui/app/routes/vault/cluster/license.js
%license ui/app/serializers/license.js
%license ui/app/styles/components/license-banners.scss
%license ui/app/templates/components/license-banners.hbs
%license ui/app/templates/components/license-info.hbs
%license ui/app/templates/vault/cluster/license.hbs
%license website/content/api-docs/system/license.mdx
%doc CHANGELOG.md CONTRIBUTING.md README.md api/README.md
%doc builtin/credential/aws/pkcs7/README.md
%doc builtin/credential/cert/test-fixtures/generate.txt command/agent/README.md
%doc physical/foundationdb/README.md plugins/database/mongodb/README.md
%doc plugins/database/mssql/README.md ui/MODULE_REPORT.md ui/README.md
%doc ui/lib/core/addon/helpers/changelog-url-for.js
%doc ui/lib/core/app/helpers/changelog-url-for.js
%doc ui/lib/core/stories/alert-banner.md ui/lib/core/stories/alert-inline.md
%doc ui/lib/core/stories/box-radio.md ui/lib/core/stories/chevron.md
%doc ui/lib/core/stories/confirm-action.md ui/lib/core/stories/confirm.md
%doc ui/lib/core/stories/doc-link.md ui/lib/core/stories/empty-state.md
%doc ui/lib/core/stories/form-field-groups.md ui/lib/core/stories/form-field.md
%doc ui/lib/core/stories/form-save-buttons.md ui/lib/core/stories/icon.md
%doc ui/lib/core/stories/info-table-row.md ui/lib/core/stories/info-table.md
%doc ui/lib/core/stories/layout-loading.md ui/lib/core/stories/linkable-item.md
%doc ui/lib/core/stories/list-view.md ui/lib/core/stories/masked-input.md
%doc ui/lib/core/stories/message-error.md ui/lib/core/stories/message.md
%doc ui/lib/core/stories/popup-menu.md ui/lib/core/stories/search-select.md
%doc ui/lib/core/stories/select.md ui/lib/core/stories/toggle-button.md
%doc ui/lib/core/stories/ttl-form.md ui/lib/core/stories/ttl-picker.md
%doc ui/lib/core/stories/ttl-picker2.md
%doc ui/lib/core/stories/vault-logo-spinner.md
%doc ui/lib/core/stories/toolbar/toolbar-actions.md
%doc ui/lib/core/stories/toolbar/toolbar-download-button.md
%doc ui/lib/core/stories/toolbar/toolbar-filters.md
%doc ui/lib/core/stories/toolbar/toolbar-link.md
%doc ui/lib/core/stories/toolbar/toolbar-secret-link.md
%doc ui/lib/core/stories/toolbar/toolbar.md ui/public/robots.txt
%doc ui/stories/alert-popup.md ui/stories/auth-form.md
%doc ui/stories/file-to-array-buffer.md ui/stories/selectable-card.md
%doc ui/stories/toggle.md ui/stories/auth-config-form/config.md
%doc ui/stories/auth-config-form/options.md website/README.md
%doc website/components/columns/README.md
%doc website/components/inline-tag/README.md docs website/content/security.mdx
%doc website/content/api-docs/index.mdx website/content/api-docs/libraries.mdx
%doc website/content/api-docs/relatedtools.mdx
%doc website/content/api-docs/auth/alicloud.mdx
%doc website/content/api-docs/auth/app-id.mdx
%doc website/content/api-docs/auth/approle.mdx
%doc website/content/api-docs/auth/aws.mdx
%doc website/content/api-docs/auth/azure.mdx
%doc website/content/api-docs/auth/cert.mdx website/content/api-docs/auth/cf.mdx
%doc website/content/api-docs/auth/gcp.mdx
%doc website/content/api-docs/auth/github.mdx
%doc website/content/api-docs/auth/index.mdx
%doc website/content/api-docs/auth/jwt.mdx
%doc website/content/api-docs/auth/kerberos.mdx
%doc website/content/api-docs/auth/kubernetes.mdx
%doc website/content/api-docs/auth/ldap.mdx
%doc website/content/api-docs/auth/oci.mdx
%doc website/content/api-docs/auth/okta.mdx
%doc website/content/api-docs/auth/radius.mdx
%doc website/content/api-docs/auth/token.mdx
%doc website/content/api-docs/auth/userpass.mdx
%doc website/content/api-docs/secret/ad.mdx
%doc website/content/api-docs/secret/alicloud.mdx
%doc website/content/api-docs/secret/aws.mdx
%doc website/content/api-docs/secret/azure.mdx
%doc website/content/api-docs/secret/cassandra.mdx
%doc website/content/api-docs/secret/consul.mdx
%doc website/content/api-docs/secret/cubbyhole.mdx
%doc website/content/api-docs/secret/gcp.mdx
%doc website/content/api-docs/secret/gcpkms.mdx
%doc website/content/api-docs/secret/index.mdx
%doc website/content/api-docs/secret/kmip.mdx
%doc website/content/api-docs/secret/mongodbatlas.mdx
%doc website/content/api-docs/secret/nomad.mdx
%doc website/content/api-docs/secret/openldap.mdx
%doc website/content/api-docs/secret/pki.mdx
%doc website/content/api-docs/secret/rabbitmq.mdx
%doc website/content/api-docs/secret/ssh.mdx
%doc website/content/api-docs/secret/terraform.mdx
%doc website/content/api-docs/secret/totp.mdx
%doc website/content/api-docs/secret/transform.mdx
%doc website/content/api-docs/secret/transit.mdx
%doc website/content/api-docs/secret/databases/cassandra.mdx
%doc website/content/api-docs/secret/databases/couchbase.mdx
%doc website/content/api-docs/secret/databases/elasticdb.mdx
%doc website/content/api-docs/secret/databases/hanadb.mdx
%doc website/content/api-docs/secret/databases/index.mdx
%doc website/content/api-docs/secret/databases/influxdb.mdx
%doc website/content/api-docs/secret/databases/mongodb.mdx
%doc website/content/api-docs/secret/databases/mongodbatlas.mdx
%doc website/content/api-docs/secret/databases/mssql.mdx
%doc website/content/api-docs/secret/databases/mysql-maria.mdx
%doc website/content/api-docs/secret/databases/oracle.mdx
%doc website/content/api-docs/secret/databases/postgresql.mdx
%doc website/content/api-docs/secret/databases/redshift.mdx
%doc website/content/api-docs/secret/databases/snowflake.mdx
%doc website/content/api-docs/secret/identity/entity-alias.mdx
%doc website/content/api-docs/secret/identity/entity.mdx
%doc website/content/api-docs/secret/identity/group-alias.mdx
%doc website/content/api-docs/secret/identity/group.mdx
%doc website/content/api-docs/secret/identity/index.mdx
%doc website/content/api-docs/secret/identity/lookup.mdx
%doc website/content/api-docs/secret/identity/tokens.mdx
%doc website/content/api-docs/secret/key-management/awskms.mdx
%doc website/content/api-docs/secret/key-management/azurekeyvault.mdx
%doc website/content/api-docs/secret/key-management/index.mdx
%doc website/content/api-docs/secret/kv/index.mdx
%doc website/content/api-docs/secret/kv/kv-v1.mdx
%doc website/content/api-docs/secret/kv/kv-v2.mdx
%doc website/content/api-docs/system/audit-hash.mdx
%doc website/content/api-docs/system/audit.mdx
%doc website/content/api-docs/system/auth.mdx
%doc website/content/api-docs/system/capabilities-accessor.mdx
%doc website/content/api-docs/system/capabilities-self.mdx
%doc website/content/api-docs/system/capabilities.mdx
%doc website/content/api-docs/system/config-auditing.mdx
%doc website/content/api-docs/system/config-control-group.mdx
%doc website/content/api-docs/system/config-cors.mdx
%doc website/content/api-docs/system/config-reload.mdx
%doc website/content/api-docs/system/config-state.mdx
%doc website/content/api-docs/system/config-ui.mdx
%doc website/content/api-docs/system/control-group.mdx
%doc website/content/api-docs/system/generate-recovery-token.mdx
%doc website/content/api-docs/system/generate-root.mdx
%doc website/content/api-docs/system/health.mdx
%doc website/content/api-docs/system/host-info.mdx
%doc website/content/api-docs/system/index.mdx
%doc website/content/api-docs/system/init.mdx
%doc website/content/api-docs/system/internal-counters.mdx
%doc website/content/api-docs/system/internal-specs-openapi.mdx
%doc website/content/api-docs/system/internal-ui-feature.mdx
%doc website/content/api-docs/system/internal-ui-mounts.mdx
%doc website/content/api-docs/system/key-status.mdx
%doc website/content/api-docs/system/leader.mdx
%doc website/content/api-docs/system/lease-count-quotas.mdx
%doc website/content/api-docs/system/leases.mdx
%doc website/content/api-docs/system/metrics.mdx
%doc website/content/api-docs/system/monitor.mdx
%doc website/content/api-docs/system/mounts.mdx
%doc website/content/api-docs/system/namespaces.mdx
%doc website/content/api-docs/system/plugins-catalog.mdx
%doc website/content/api-docs/system/plugins-reload-backend.mdx
%doc website/content/api-docs/system/policies-password.mdx
%doc website/content/api-docs/system/policies.mdx
%doc website/content/api-docs/system/policy.mdx
%doc website/content/api-docs/system/pprof.mdx
%doc website/content/api-docs/system/quotas-config.mdx
%doc website/content/api-docs/system/rate-limit-quotas.mdx
%doc website/content/api-docs/system/raw.mdx
%doc website/content/api-docs/system/rekey-recovery-key.mdx
%doc website/content/api-docs/system/rekey.mdx
%doc website/content/api-docs/system/remount.mdx
%doc website/content/api-docs/system/rotate-config.mdx
%doc website/content/api-docs/system/rotate.mdx
%doc website/content/api-docs/system/seal-status.mdx
%doc website/content/api-docs/system/seal.mdx
%doc website/content/api-docs/system/sealwrap-rewrap.mdx
%doc website/content/api-docs/system/step-down.mdx
%doc website/content/api-docs/system/tools.mdx
%doc website/content/api-docs/system/unseal.mdx
%doc website/content/api-docs/system/wrapping-lookup.mdx
%doc website/content/api-docs/system/wrapping-rewrap.mdx
%doc website/content/api-docs/system/wrapping-unwrap.mdx
%doc website/content/api-docs/system/wrapping-wrap.mdx
%doc website/content/api-docs/system/mfa/duo.mdx
%doc website/content/api-docs/system/mfa/index.mdx
%doc website/content/api-docs/system/mfa/okta.mdx
%doc website/content/api-docs/system/mfa/pingid.mdx
%doc website/content/api-docs/system/mfa/totp.mdx
%doc website/content/api-docs/system/replication/index.mdx
%doc website/content/api-docs/system/replication/replication-dr.mdx
%doc website/content/api-docs/system/replication/replication-performance.mdx
%doc website/content/api-docs/system/storage/index.mdx
%doc website/content/api-docs/system/storage/raft.mdx
%doc website/content/api-docs/system/storage/raftautopilot.mdx
%doc website/content/api-docs/system/storage/raftautosnapshots.mdx
%doc website/content/guides/getting-started.mdx website/content/guides/index.mdx
%doc website/content/guides/encryption/index.mdx
%doc website/content/guides/encryption/spring-demo.mdx
%doc website/content/guides/encryption/transit-rewrap.mdx
%doc website/content/guides/encryption/transit.mdx
%doc website/content/guides/identity/approle-trusted-entities.mdx
%doc website/content/guides/identity/authentication.mdx
%doc website/content/guides/identity/control-groups.mdx
%doc website/content/guides/identity/identity.mdx
%doc website/content/guides/identity/index.mdx
%doc website/content/guides/identity/lease.mdx
%doc website/content/guides/identity/policies.mdx
%doc website/content/guides/identity/policy-templating.mdx
%doc website/content/guides/identity/secure-intro.mdx
%doc website/content/guides/identity/sentinel.mdx
%doc website/content/guides/operations/autounseal-aws-kms.mdx
%doc website/content/guides/operations/deployment-guide.mdx
%doc website/content/guides/operations/disaster-recovery.mdx
%doc website/content/guides/operations/generate-root.mdx
%doc website/content/guides/operations/index.mdx
%doc website/content/guides/operations/monitoring.mdx
%doc website/content/guides/operations/mount-filter.mdx
%doc website/content/guides/operations/multi-tenant.mdx
%doc website/content/guides/operations/performance-nodes.mdx
%doc website/content/guides/operations/plugin-backends.mdx
%doc website/content/guides/operations/production.mdx
%doc website/content/guides/operations/reference-architecture.mdx
%doc website/content/guides/operations/rekeying-and-rotating.mdx
%doc website/content/guides/operations/replication.mdx
%doc website/content/guides/operations/seal-wrap.mdx
%doc website/content/guides/operations/vault-ha-consul.mdx
%doc website/content/guides/secret-mgmt/app-integration.mdx
%doc website/content/guides/secret-mgmt/cubbyhole.mdx
%doc website/content/guides/secret-mgmt/db-root-rotation.mdx
%doc website/content/guides/secret-mgmt/dynamic-secrets.mdx
%doc website/content/guides/secret-mgmt/index.mdx
%doc website/content/guides/secret-mgmt/pki-engine.mdx
%doc website/content/guides/secret-mgmt/ssh-otp.mdx
%doc website/content/guides/secret-mgmt/static-secrets.mdx
%doc website/content/guides/secret-mgmt/versioned-kv.mdx
%doc website/content/intro/index.mdx
%doc website/content/intro/getting-started/apis.mdx
%doc website/content/intro/getting-started/authentication.mdx
%doc website/content/intro/getting-started/deploy.mdx
%doc website/content/intro/getting-started/dev-server.mdx
%doc website/content/intro/getting-started/dynamic-secrets.mdx
%doc website/content/intro/getting-started/first-secret.mdx
%doc website/content/intro/getting-started/help.mdx
%doc website/content/intro/getting-started/index.mdx
%doc website/content/intro/getting-started/next-steps.mdx
%doc website/content/intro/getting-started/policies.mdx
%doc website/content/intro/getting-started/secrets-engines.mdx
%doc website/content/partials/aws-auth-metadata-fix.mdx
%doc website/content/partials/aws-auth-metadata-issue.mdx
%doc website/content/partials/aws-imds-timeout-upgrade.mdx
%doc website/content/partials/aws-imds-timeout.mdx
%doc website/content/partials/aws-invalid-header-fix.mdx
%doc website/content/partials/aws-invalid-header.mdx
%doc website/content/partials/aws-sts-issue.mdx
%doc website/content/partials/builds-without-ui.mdx
%doc website/content/partials/enterprise-licenses.mdx
%doc website/content/partials/ldap-upndomain-issue.mdx
%doc website/content/partials/okta-group-pagination.mdx
%doc website/content/partials/primary-cluster-addr-change.mdx
%doc website/content/partials/tokenfields.mdx
%doc website/content/partials/tokenstorefields.mdx
%doc website/content/partials/transform-upgrade.mdx docs docs
%doc changelog/10072.txt changelog/10077.txt changelog/10131.txt
%doc changelog/10181.txt changelog/10231.txt changelog/10365.txt
%doc changelog/10375.txt changelog/10384.txt changelog/10386.txt
%doc changelog/10416.txt changelog/10417.txt changelog/10424.txt
%doc changelog/10433.txt changelog/10444.txt changelog/10456.txt
%doc changelog/10487.txt changelog/10489.txt changelog/10490.txt
%doc changelog/10491.txt changelog/10498.txt changelog/10514.txt
%doc changelog/10520.txt changelog/10536.txt changelog/10537.txt
%doc changelog/10546.txt changelog/10556.txt changelog/10558.txt
%doc changelog/10579.txt changelog/10588.txt changelog/10596.txt
%doc changelog/10603.txt changelog/10609.txt changelog/10613.txt
%doc changelog/10650.txt changelog/10653.txt changelog/10655.txt
%doc changelog/10677.txt changelog/10684.txt changelog/10689.txt
%doc changelog/10705.txt changelog/10708.txt changelog/10725.txt
%doc changelog/10726.txt changelog/10730.txt changelog/10743.txt
%doc changelog/10744.txt changelog/10756.txt changelog/10757.txt
%doc changelog/10758.txt changelog/10759.txt changelog/10766.txt
%doc changelog/10767.txt changelog/10812.txt changelog/10826.txt
%doc changelog/10833.txt changelog/10834.txt changelog/10848.txt
%doc changelog/10850.txt changelog/10855.txt changelog/10858.txt
%doc changelog/10877.txt changelog/10901.txt changelog/10904.txt
%doc changelog/10906.txt changelog/10919.txt changelog/10927.txt
%doc changelog/10931.txt changelog/10938.txt changelog/10942.txt
%doc changelog/10949.txt changelog/10951.txt changelog/10952.txt
%doc changelog/10953.txt changelog/10964.txt changelog/10980.txt
%doc changelog/10982.txt changelog/10992.txt changelog/10995.txt
%doc changelog/10996.txt changelog/10997.txt changelog/11011.txt
%doc changelog/11015.txt changelog/11018.txt changelog/11022.txt
%doc changelog/11094.txt changelog/11113.txt changelog/11119.txt
%doc changelog/11127.txt changelog/11129.txt changelog/11142.txt
%doc changelog/11143.txt changelog/11182.txt changelog/11213.txt
%doc changelog/11226.txt changelog/11231.txt changelog/11247.txt
%doc changelog/11252.txt changelog/11256.txt changelog/11258.txt
%doc changelog/11259.txt changelog/11260.txt changelog/11262.txt
%doc changelog/11269.txt changelog/11283.txt changelog/11284.txt
%doc changelog/11288.txt changelog/11289.txt changelog/11294.txt
%doc changelog/11324.txt changelog/11345.txt changelog/11360.txt
%doc changelog/11364.txt changelog/11365.txt changelog/11366.txt
%doc changelog/11367.txt changelog/11371.txt changelog/11377.txt
%doc changelog/11388.txt changelog/11404.txt changelog/11408.txt
%doc changelog/11442.txt changelog/11447.txt changelog/11451.txt
%doc changelog/11453.txt changelog/11473.txt changelog/11495.txt
%doc changelog/11500.txt changelog/11502.txt changelog/11506.txt
%doc changelog/11517.txt changelog/11530.txt changelog/11532.txt
%doc changelog/11541.txt changelog/11562.txt changelog/11576.txt
%doc changelog/11585.txt changelog/11586.txt changelog/11588.txt
%doc changelog/11596.txt changelog/11597.txt changelog/11600.txt
%doc changelog/11607.txt changelog/11628.txt changelog/11638.txt
%doc changelog/11641.txt changelog/11647.txt changelog/11650.txt
%doc changelog/11672.txt changelog/11680.txt changelog/11696.txt
%doc changelog/11705.txt changelog/11708.txt changelog/11759.txt
%doc changelog/11775.txt changelog/11778.txt changelog/11784.txt
%doc changelog/11785.txt changelog/11795.txt changelog/11796.txt
%doc changelog/11802.txt changelog/11820.txt changelog/11826.txt
%doc changelog/11836.txt changelog/11838.txt changelog/11861.txt
%doc changelog/11864.txt changelog/11872.txt changelog/11878.txt
%doc changelog/11884.txt changelog/11895.txt changelog/11899.txt
%doc changelog/11907.txt changelog/11934.txt changelog/11942.txt
%doc changelog/11956.txt changelog/11957.txt changelog/11958.txt
%doc changelog/11963.txt changelog/11970.txt changelog/11975.txt
%doc changelog/11984.txt changelog/11992.txt changelog/11995.txt
%doc changelog/11997.txt changelog/12003.txt changelog/12008.txt
%doc changelog/12016.txt changelog/12019.txt changelog/12020.txt
%doc changelog/12023.txt changelog/12024.txt changelog/12025.txt
%doc changelog/12026.txt changelog/12031.txt changelog/12034.txt
%doc changelog/12035.txt changelog/12042.txt changelog/12049.txt
%doc changelog/12071.txt changelog/12073.txt changelog/12079.txt
%doc changelog/12087.txt changelog/12111.txt changelog/12151.txt
%doc changelog/12163.txt changelog/12175.txt changelog/12229.txt
%doc changelog/12245.txt changelog/12258.txt changelog/12300.txt
%doc changelog/12339.txt changelog/12340.txt changelog/12348.txt
%doc changelog/12351.txt changelog/12354.txt changelog/12371.txt
%doc changelog/12377.txt changelog/12378.txt changelog/12379.txt
%doc changelog/12388.txt changelog/12408.txt changelog/12409.txt
%doc changelog/12418.txt changelog/12473.txt changelog/12478.txt
%doc changelog/12514.txt changelog/12534.txt changelog/12550.txt
%doc changelog/12563.txt changelog/12599.txt changelog/12635.txt
%doc changelog/9972.txt changelog/README.md changelog/_ 1686.txt
%doc changelog/_10959.txt changelog/_1622.txt changelog/_1633.txt
%doc changelog/_1637.txt changelog/_1642.txt changelog/_1656.txt
%doc changelog/_1659.txt changelog/_1663.txt changelog/_1680.txt
%doc changelog/_1691.txt changelog/_1705.txt changelog/_1712.txt
%doc changelog/_1739.txt changelog/_1757.txt changelog/_1792.txt
%doc changelog/_1819.txt changelog/_2021Jan20.txt changelog/_2021Jan26.txt
%doc changelog/_2021Jul21_license.txt changelog/_2071.txt
%doc changelog/changelog.tmpl dependencies/2-25-21/deps-upgrade-output.txt
%doc dependencies/2-25-21/deps-upgrade.txt internalshared/README.md
%doc sdk/README.md sdk/database/dbplugin/README.md sdk/queue/README.md
%doc serviceregistration/kubernetes/testing/README.md terraform/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 1.8.3-1%{?dist}
- Initial package

