# Generated by go2rpm 1.5.0

# https://github.com/aerospike/aerospike-client-go
%global goipath         github.com/aerospike/aerospike-client-go
Version:                5.6.0

%gometa

%global common_description %{expand:
Aerospike Client Go.}

%global golicenses      LICENSE pkg/bcrypt/LICENSE
%global godocs          docs examples CHANGELOG.md README.md\\\
                        pkg/bcrypt/README tools/benchmark/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Aerospike Client Go

# Upstream license specification: Apache-2.0 and BSD-3-Clause
License:        ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/yuin/gopher-lua)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(golang.org/x/sync/semaphore)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in tools/benchmark tools/cli tools/asinfo; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%files
%license LICENSE pkg/bcrypt/LICENSE
%doc docs examples CHANGELOG.md README.md pkg/bcrypt/README
%doc tools/benchmark/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 5.6.0-1%{?dist}
- Initial package

