# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/nu7hatch/gouuid
%global goipath         github.com/nu7hatch/gouuid
%global commit          179d4d0c4d8d407a32af483c2354df1d2c91e6c3

%gometa

%global common_description %{expand:
Go binding for libuuid.}

%global golicenses      COPYING
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go binding for libuuid

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0-0.1%{?dist}.20211006git179d4d0
- Initial package

