# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/cheggaaa/pb
%global goipath         github.com/cheggaaa/pb
Version:                3.0.8

%gometa

%global common_description %{expand:
Console progress bar for Golang.}

%global golicenses      LICENSE v3/LICENSE
%global godocs          README_V1.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Console progress bar for Golang

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/mattn/go-colorable)
BuildRequires:  golang(github.com/mattn/go-isatty)
BuildRequires:  golang(github.com/mattn/go-runewidth)
BuildRequires:  golang(github.com/VividCortex/ewma)
BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 3.0.8-1%{?dist}
- Initial package

