# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/google/google-api-go-client
%global goipath         github.com/google/google-api-go-client
Version:                0.58.0

%gometa

%global common_description %{expand:
Auto-generated Google APIs for Go.}

%global golicenses      LICENSE
%global godocs          docs examples AUTHORS CHANGES.md CODE_OF_CONDUCT.md\\\
                        CONTRIBUTING.md CONTRIBUTORS GettingStarted.md\\\
                        README.md RELEASING.md SECURITY.md TODO testing.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Auto-generated Google APIs for Go

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/compute/metadata)
BuildRequires:  golang(github.com/googleapis/gax-go/v2)
BuildRequires:  golang(go.opencensus.io/plugin/ocgrpc)
BuildRequires:  golang(go.opencensus.io/plugin/ochttp)
BuildRequires:  golang(go.opencensus.io/trace)
BuildRequires:  golang(go.opencensus.io/trace/propagation)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/oauth2/google)
BuildRequires:  golang(golang.org/x/sync/semaphore)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(google.golang.org/api/books/v1)
BuildRequires:  golang(google.golang.org/api/calendar/v3)
BuildRequires:  golang(google.golang.org/api/compute/v1)
BuildRequires:  golang(google.golang.org/api/customsearch/v1)
BuildRequires:  golang(google.golang.org/api/drive/v2)
BuildRequires:  golang(google.golang.org/api/fitness/v1)
BuildRequires:  golang(google.golang.org/api/gmail/v1)
BuildRequires:  golang(google.golang.org/api/google-api-go-generator/internal/disco)
BuildRequires:  golang(google.golang.org/api/googleapi)
BuildRequires:  golang(google.golang.org/api/googleapi/transport)
BuildRequires:  golang(google.golang.org/api/internal)
BuildRequires:  golang(google.golang.org/api/internal/gensupport)
BuildRequires:  golang(google.golang.org/api/internal/impersonate)
BuildRequires:  golang(google.golang.org/api/internal/third_party/uritemplates)
BuildRequires:  golang(google.golang.org/api/internal/version)
BuildRequires:  golang(google.golang.org/api/iterator)
BuildRequires:  golang(google.golang.org/api/mirror/v1)
BuildRequires:  golang(google.golang.org/api/option)
BuildRequires:  golang(google.golang.org/api/option/internaloption)
BuildRequires:  golang(google.golang.org/api/tasks/v1)
BuildRequires:  golang(google.golang.org/api/translate/v3)
BuildRequires:  golang(google.golang.org/api/transport/cert)
BuildRequires:  golang(google.golang.org/api/transport/grpc)
BuildRequires:  golang(google.golang.org/api/transport/http)
BuildRequires:  golang(google.golang.org/api/transport/http/internal/propagation)
BuildRequires:  golang(google.golang.org/api/transport/internal/dca)
BuildRequires:  golang(google.golang.org/api/urlshortener/v1)
BuildRequires:  golang(google.golang.org/api/youtube/v3)
BuildRequires:  golang(google.golang.org/genproto/googleapis/bytestream)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/balancer/grpclb)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/credentials/google)
BuildRequires:  golang(google.golang.org/grpc/credentials/oauth)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(google.golang.org/api/cloudresourcemanager/v1)
BuildRequires:  golang(google.golang.org/api/monitoring/v3)
BuildRequires:  golang(google.golang.org/api/storage/v1)
BuildRequires:  golang(google.golang.org/api/transport/bytestream/internal)
BuildRequires:  golang(google.golang.org/grpc/metadata)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in google-api-go-generator; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs examples AUTHORS CHANGES.md CODE_OF_CONDUCT.md CONTRIBUTING.md
%doc CONTRIBUTORS GettingStarted.md README.md RELEASING.md SECURITY.md TODO
%doc testing.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0.58.0-1%{?dist}
- Initial package

