# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/dylanmei/iso8601
%global goipath         github.com/dylanmei/iso8601
Version:                0.1.0

%gometa

%global common_description %{expand:
An ISO8601 Go utility.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        An ISO8601 Go utility

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0.1.0-1%{?dist}
- Initial package

