# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/mitchellh/go-fs
%global goipath         github.com/mitchellh/go-fs
%global commit          b7b9ca407ffff465de12fc37ccbb81ea8b428c43

%gometa

%global common_description %{expand:
Filesystem library for Go, implementing FAT filesystems so far.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Filesystem library for Go, implementing FAT filesystems so far

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0-0.1%{?dist}.20211006gitb7b9ca4
- Initial package

