# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/hashicorp/packer-plugin-sdk
%global goipath         github.com/hashicorp/packer-plugin-sdk
Version:                0.2.6

%gometa

%global common_description %{expand:
Packer Plugin SDK enables building Packer plugins (builders, provisioners, or
post-processors) to manage any service providers or custom in-house solutions.}

%global golicenses      LICENSE multistep/LICENSE.md
%global godocs          CHANGELOG.md README.md acctest/provisioneracc/test-\\\
                        fixtures/amazon-ebs/amazon-ebs.txt\\\
                        acctest/provisioneracc/test-fixtures/amazon-\\\
                        ebs/amazon-ebs_windows.txt\\\
                        acctest/provisioneracc/test-fixtures/amazon-\\\
                        ebs/scripts/bootstrap_win.txt\\\
                        acctest/provisioneracc/test-\\\
                        fixtures/virtualbox/virtualbox-iso.txt cmd/packer-\\\
                        sdc/README.md multistep/commonsteps/test-\\\
                        fixtures/SomeDir/myfile.txt\\\
                        multistep/commonsteps/test-fixtures/root/another.txt\\\
                        multistep/commonsteps/test-\\\
                        fixtures/root/another.txt.sha1sum\\\
                        multistep/commonsteps/test-fixtures/root/basic.txt\\\
                        multistep/commonsteps/test-\\\
                        fixtures/root/basic.txt.sha1sum test-\\\
                        fixtures/SomeDir/myfile.txt

Name:           %{goname}
Release:        1%{?dist}
Summary:        Packer Plugin SDK enables building Packer plugins (builders, provisioners, or post-processors) to manage any service providers or custom in-house solutions

# Upstream license specification: MPL-2.0 and MIT
License:        MPLv2.0 and MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/agext/levenshtein)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/secretsmanager)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/secretsmanager/secretsmanageriface)
BuildRequires:  golang(github.com/fatih/camelcase)
BuildRequires:  golang(github.com/fatih/structtag)
BuildRequires:  golang(github.com/gofrs/flock)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/shlex)
BuildRequires:  golang(github.com/google/uuid)
BuildRequires:  golang(github.com/hashicorp/consul/api)
BuildRequires:  golang(github.com/hashicorp/go-getter/gcs/v2)
BuildRequires:  golang(github.com/hashicorp/go-getter/s3/v2)
BuildRequires:  golang(github.com/hashicorp/go-getter/v2)
BuildRequires:  golang(github.com/hashicorp/go-getter/v2/helper/url)
BuildRequires:  golang(github.com/hashicorp/go-multierror)
BuildRequires:  golang(github.com/hashicorp/go-version)
BuildRequires:  golang(github.com/hashicorp/hcl/v2/hcldec)
BuildRequires:  golang(github.com/hashicorp/vault/api)
BuildRequires:  golang(github.com/hashicorp/yamux)
BuildRequires:  golang(github.com/jehiah/go-strftime)
BuildRequires:  golang(github.com/masterzen/winrm)
BuildRequires:  golang(github.com/mitchellh/cli)
BuildRequires:  golang(github.com/mitchellh/go-fs)
BuildRequires:  golang(github.com/mitchellh/go-fs/fat)
BuildRequires:  golang(github.com/mitchellh/iochan)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/mitchellh/reflectwalk)
BuildRequires:  golang(github.com/packer-community/winrmcp/winrmcp)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/pkg/sftp)
BuildRequires:  golang(github.com/ryanuber/go-glob)
BuildRequires:  golang(github.com/ugorji/go/codec)
BuildRequires:  golang(github.com/zclconf/go-cty/cty)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/gocty)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/json)
BuildRequires:  golang(golang.org/x/crypto/ssh)
BuildRequires:  golang(golang.org/x/crypto/ssh/agent)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)
BuildRequires:  golang(golang.org/x/mobile/event/key)
BuildRequires:  golang(golang.org/x/net/http/httpproxy)
BuildRequires:  golang(golang.org/x/net/proxy)
BuildRequires:  golang(golang.org/x/tools/go/packages)
BuildRequires:  golang(golang.org/x/tools/imports)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/dylanmei/winrmtest)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(golang.org/x/crypto/ed25519)
BuildRequires:  golang(golang.org/x/mod/sumdb/dirhash)
BuildRequires:  golang(golang.org/x/sync/errgroup)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE multistep/LICENSE.md
%doc CHANGELOG.md README.md
%doc acctest/provisioneracc/test-fixtures/amazon-ebs/amazon-ebs.txt
%doc acctest/provisioneracc/test-fixtures/amazon-ebs/amazon-ebs_windows.txt
%doc acctest/provisioneracc/test-fixtures/amazon-ebs/scripts/bootstrap_win.txt
%doc acctest/provisioneracc/test-fixtures/virtualbox/virtualbox-iso.txt
%doc cmd/packer-sdc/README.md
%doc multistep/commonsteps/test-fixtures/SomeDir/myfile.txt
%doc multistep/commonsteps/test-fixtures/root/another.txt
%doc multistep/commonsteps/test-fixtures/root/another.txt.sha1sum
%doc multistep/commonsteps/test-fixtures/root/basic.txt
%doc multistep/commonsteps/test-fixtures/root/basic.txt.sha1sum
%doc test-fixtures/SomeDir/myfile.txt
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0.2.6-1%{?dist}
- Initial package

