# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/hashicorp/packer-plugin-yandex
%global goipath         github.com/hashicorp/packer-plugin-yandex
Version:                1.0.2

%gometa

%global common_description %{expand:
Packer plugin for Yandex Compute Builder.}

%global golicenses      LICENSE
%global godocs          docs example CHANGELOG.md README.md docs-\\\
                        partials/builder/yandex/AccessConfig-not-required.mdx\\\
                        docs-partials/builder/yandex/AccessConfig-\\\
                        required.mdx docs-\\\
                        partials/builder/yandex/AccessConfig.mdx docs-\\\
                        partials/builder/yandex/CloudConfig-required.mdx\\\
                        docs-partials/builder/yandex/CommonConfig-not-\\\
                        required.mdx docs-partials/builder/yandex/Config-not-\\\
                        required.mdx docs-partials/builder/yandex/DiskConfig-\\\
                        not-required.mdx docs-\\\
                        partials/builder/yandex/ImageConfig-not-required.mdx\\\
                        docs-partials/builder/yandex/InstanceConfig-not-\\\
                        required.mdx docs-\\\
                        partials/builder/yandex/NetworkConfig-not-\\\
                        required.mdx docs-\\\
                        partials/builder/yandex/SourceImageConfig-not-\\\
                        required.mdx docs-\\\
                        partials/builder/yandex/SourceImageConfig-\\\
                        required.mdx docs-partials/post-processor/yandex-\\\
                        export/Config-not-required.mdx docs-partials/post-\\\
                        processor/yandex-export/Config-required.mdx docs-\\\
                        partials/post-processor/yandex-export/ExchangeConfig-\\\
                        required.mdx docs-partials/post-processor/yandex-\\\
                        import/Config-not-required.mdx docs

Name:           %{goname}
Release:        1%{?dist}
Summary:        Packer plugin for Yandex Compute Builder

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/s3)
BuildRequires:  golang(github.com/c2h5oh/datasize)
BuildRequires:  golang(github.com/google/uuid)
BuildRequires:  golang(github.com/grpc-ecosystem/go-grpc-middleware)
BuildRequires:  golang(github.com/hashicorp/hcl/v2/hcldec)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/common)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/communicator)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/multistep)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/multistep/commonsteps)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/packer)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/packerbuilderdata)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/plugin)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/template/config)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/template/interpolate)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/useragent)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/uuid)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/version)
BuildRequires:  golang(github.com/yandex-cloud/go-genproto/yandex/cloud/compute/v1)
BuildRequires:  golang(github.com/yandex-cloud/go-genproto/yandex/cloud/endpoint)
BuildRequires:  golang(github.com/yandex-cloud/go-genproto/yandex/cloud/iam/v1)
BuildRequires:  golang(github.com/yandex-cloud/go-genproto/yandex/cloud/iam/v1/awscompatibility)
BuildRequires:  golang(github.com/yandex-cloud/go-genproto/yandex/cloud/vpc/v1)
BuildRequires:  golang(github.com/yandex-cloud/go-sdk)
BuildRequires:  golang(github.com/yandex-cloud/go-sdk/iamkey)
BuildRequires:  golang(github.com/yandex-cloud/go-sdk/pkg/requestid)
BuildRequires:  golang(github.com/yandex-cloud/go-sdk/pkg/retry)
BuildRequires:  golang(github.com/yandex-cloud/go-sdk/sdkresolvers)
BuildRequires:  golang(github.com/zclconf/go-cty/cty)
BuildRequires:  golang(golang.org/x/crypto/ssh)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/go-resty/resty/v2)
BuildRequires:  golang(github.com/hashicorp/packer-plugin-sdk/acctest)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/packer-plugin-yandex %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs example CHANGELOG.md README.md
%doc docs-partials/builder/yandex/AccessConfig-not-required.mdx
%doc docs-partials/builder/yandex/AccessConfig-required.mdx
%doc docs-partials/builder/yandex/AccessConfig.mdx
%doc docs-partials/builder/yandex/CloudConfig-required.mdx
%doc docs-partials/builder/yandex/CommonConfig-not-required.mdx
%doc docs-partials/builder/yandex/Config-not-required.mdx
%doc docs-partials/builder/yandex/DiskConfig-not-required.mdx
%doc docs-partials/builder/yandex/ImageConfig-not-required.mdx
%doc docs-partials/builder/yandex/InstanceConfig-not-required.mdx
%doc docs-partials/builder/yandex/NetworkConfig-not-required.mdx
%doc docs-partials/builder/yandex/SourceImageConfig-not-required.mdx
%doc docs-partials/builder/yandex/SourceImageConfig-required.mdx
%doc docs-partials/post-processor/yandex-export/Config-not-required.mdx
%doc docs-partials/post-processor/yandex-export/Config-required.mdx
%doc docs-partials/post-processor/yandex-export/ExchangeConfig-required.mdx
%doc docs-partials/post-processor/yandex-import/Config-not-required.mdx docs
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 1.0.2-1%{?dist}
- Initial package

