# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/packer-community/winrmcp
%global goipath         github.com/packer-community/winrmcp
%global commit          c76d91c1e7db27b0868c5d09e292bb540616c9a2

%gometa

%global common_description %{expand:
Copy files to a remote host using WinRM.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Copy files to a remote host using WinRM

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/dylanmei/iso8601)
BuildRequires:  golang(github.com/masterzen/winrm)
BuildRequires:  golang(github.com/nu7hatch/gouuid)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/winrmcp %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0-0.1%{?dist}.20211006gitc76d91c
- Initial package

