# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/mitchellh/iochan
%global goipath         github.com/mitchellh/iochan
Version:                1.0.0

%gometa

%global common_description %{expand:
A Go library for turning `io.Reader` into channels.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A Go library for turning `io.Reader` into channels

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 1.0.0-1%{?dist}
- Initial package

