# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/joyent/triton-go
%global goipath         github.com/joyent/triton-go
Version:                1.8.5

%gometa

%global common_description %{expand:
Go SDK for Joyent Triton (Compute) and Triton Object Storage (Manta).}

%global golicenses      LICENSE
%global godocs          examples README.md CHANGELOG.md docs docs

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go SDK for Joyent Triton (Compute) and Triton Object Storage (Manta)

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/abdullin/seq)
BuildRequires:  golang(github.com/dustin/go-humanize)
BuildRequires:  golang(github.com/imdario/mergo)
BuildRequires:  golang(github.com/jackc/pgx)
BuildRequires:  golang(github.com/mattn/go-isatty)
BuildRequires:  golang(github.com/olekukonko/tablewriter)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/rs/zerolog)
BuildRequires:  golang(github.com/rs/zerolog/log)
BuildRequires:  golang(github.com/sean-/conswriter)
BuildRequires:  golang(github.com/sean-/seed)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/cobra/doc)
BuildRequires:  golang(github.com/spf13/pflag)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(golang.org/x/crypto/ssh)
BuildRequires:  golang(golang.org/x/crypto/ssh/agent)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc examples README.md CHANGELOG.md docs docs
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 1.8.5-1%{?dist}
- Initial package

