# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/hashicorp/go-gatedio
%global goipath         github.com/hashicorp/go-gatedio
Version:                0.5.0

%gometa

%global common_description %{expand:
Provides a unified interface for wrapping io objects in a mutex.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Provides a unified interface for wrapping io objects in a mutex

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0.5.0-1%{?dist}
- Initial package

