# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/hashicorp/go-discover
%global goipath         github.com/hashicorp/go-discover
%global commit          c573d69da192ae69d5386b65b64353832677aad8

%gometa

%global common_description %{expand:
Discover nodes in cloud environments.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Discover nodes in cloud environments

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/defaults)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/ec2metadata)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/ec2)
BuildRequires:  golang(github.com/Azure/azure-sdk-for-go/services/network/mgmt/2015-06-15/network)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure/auth)
BuildRequires:  golang(github.com/denverdino/aliyungo/common)
BuildRequires:  golang(github.com/denverdino/aliyungo/ecs)
BuildRequires:  golang(github.com/digitalocean/godo)
BuildRequires:  golang(github.com/gophercloud/gophercloud)
BuildRequires:  golang(github.com/gophercloud/gophercloud/openstack)
BuildRequires:  golang(github.com/gophercloud/gophercloud/openstack/compute/v2/servers)
BuildRequires:  golang(github.com/gophercloud/gophercloud/pagination)
BuildRequires:  golang(github.com/hashicorp/go-multierror)
BuildRequires:  golang(github.com/hashicorp/mdns)
BuildRequires:  golang(github.com/hashicorp/vic/pkg/vsphere/tags)
BuildRequires:  golang(github.com/joyent/triton-go)
BuildRequires:  golang(github.com/joyent/triton-go/authentication)
BuildRequires:  golang(github.com/joyent/triton-go/compute)
BuildRequires:  golang(github.com/linode/linodego)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/nicolai86/scaleway-sdk)
BuildRequires:  golang(github.com/packethost/packngo)
BuildRequires:  golang(github.com/softlayer/softlayer-go/filter)
BuildRequires:  golang(github.com/softlayer/softlayer-go/services)
BuildRequires:  golang(github.com/softlayer/softlayer-go/session)
BuildRequires:  golang(github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common)
BuildRequires:  golang(github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile)
BuildRequires:  golang(github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312)
BuildRequires:  golang(github.com/vmware/govmomi)
BuildRequires:  golang(github.com/vmware/govmomi/find)
BuildRequires:  golang(github.com/vmware/govmomi/object)
BuildRequires:  golang(github.com/vmware/govmomi/vim25/mo)
BuildRequires:  golang(github.com/vmware/govmomi/vim25/types)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/oauth2/google)
BuildRequires:  golang(google.golang.org/api/compute/v1)
BuildRequires:  golang(k8s.io/api/core/v1)
BuildRequires:  golang(k8s.io/apimachinery/pkg/apis/meta/v1)
BuildRequires:  golang(k8s.io/client-go/kubernetes)
BuildRequires:  golang(k8s.io/client-go/plugin/pkg/client/auth)
BuildRequires:  golang(k8s.io/client-go/rest)
BuildRequires:  golang(k8s.io/client-go/tools/clientcmd)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 0-0.1%{?dist}.20211006gitc573d69
- Initial package

