# Generated by go2rpm
%bcond_without check

# https://github.com/mitchellh/cli
%global goipath         github.com/zclconf/go-cty-yaml
Version:                1.0.2

%gometa

%global common_description %{expand:
A package for go that helps track typing information}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library for tracking type information

# Upstream license specification: MPL-2.0
License:        MIT
URL:            %{gourl}
Source0:        https://%{goipath}/archive/v%{version}.tar.gz

BuildRequires:  golang(github.com/zclconf/go-cty/cty)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Oct 5 2021 Greg Hellings <greg.hellings@gmail.com> - 1.0.2-1
- First attempt to package
