# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/mitchellh/panicwrap
%global goipath         github.com/mitchellh/panicwrap
Version:                1.0.0

%gometa

%global common_description %{expand:
Panicwrap is a Go library for catching and handling panics in Go applications.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Panicwrap is a Go library for catching and handling panics in Go applications

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Oct 06 2021 Gregory Hellings <greg.hellings@gmail.com> - 1.0.0-1%{?dist}
- Initial package
