# Generated by go2rpm
%bcond_without check

%global gitrev 5733675afd5162de652b410d2244d82b00a38a79

# https://github.com/mitchellh/cli
%global goipath         github.com/mitchellh/prefixedio
Version:                0^20121005git5733675

%gometa

%global common_description %{expand:
A package for Go that takes an io.Reader and de-multiplexes line-oriented data based on a line prefix to a set of readers.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library for implementing command-line interfaces

# Upstream license specification: MPL-2.0
License:        MIT
URL:            %{gourl}
Source0:        https://github.com/mitchellh/prefixedio/archive/%{gitrev}.tar.gz

%description
%{common_description}

%gopkg

%prep
tar xaf %{SOURCE0}
mv prefixedio-%{gitrev} prefixedio-%{version}
tar caf %{SOURCE0} prefixedio-%{version}
rm -r prefixedio-%{version}
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Oct 5 2021 Greg Hellings <greg.hellings@gmail.com> - 0^202101005git5733675-1
- First attempt to package
